FEATURE_FULL_NAMES = {
    "az_max": "Vertical G-Force Peak",
    "az_mean": "Average Vertical G-Force",
    "ay_abs_p95": "Lateral G-Force Intensity (95th Pct)",
    "ay_signed_mean": "Average Directional Side-Force",
    "ay_signed_p95": "Peak Directional Side-Force",
    "ay_zero_cross_rate": "Steering Activity / Wobble Rate",
    "ax_jerk_rms": "Longitudinal Smoothness (Jerk)",
    "ay_jerk_rms": "Lateral Smoothness (Jerk)",
    "g_total_max": "Peak Total Combined G-Force",
    "g_lat_vert_p95": "Lateral-to-Vertical Force Ratio",
    "ax_p95_abs": "Peak Longitudinal G-Force",
    "wiggle_count": "Wiggle Count",
    "gyro_mag_peak": "Angular Velocity Peak",
    "gyro_z_peak_abs": "Yaw Rate Peak",
    "gyro_z_clean_ratio": "Steering Efficiency Ratio",
    "gyro_z_sign_flips_per_s": "Steering Reversal Rate",
    "gyro_jerk_rms": "Angular Movement Smoothness",

    "target_time": "Final Run Time",
    "n_segments": "Total Segment Count",
    "n_curves": "Total Curves Count",
    "n_straights": "Total Straights Count",

    "early_az_mean": "Early Ride: Average Vertical Gs",
    "late_az_mean": "Late Ride: Average Vertical Gs",
    "early_jerk_rms": "Early Ride: Smoothness (Jerk)",
    "late_jerk_rms": "Late Ride: Smoothness (Jerk)",
    "early_ay_zcr": "Early Ride: Steering Wobble",
    "late_ay_zcr": "Late Ride: Steering Wobble",

    "avg_ay_zcr_curves": "Overall: Avg Steering Wobble (Curves)",
    "avg_ay_zcr_straights": "Overall: Avg Steering Wobble (Straights)",
    "avg_jerk_rms": "Overall: Avg Smoothness (Jerk)",
    "max_jerk_rms": "Overall: Max Smoothness (Jerk)",
    "curve_vs_straight_jerk_ratio": "Overall: Curve/Straight Smoothness Ratio",
    "g_total_max_overall": "Overall: Max Total G-Force",
    "g_total_mean_overall": "Overall: Avg Total G-Force",
    "g_lat_vert_p95_avg": "Overall: Avg Lateral/Vertical Ratio",
    "g_lat_vert_p95_max": "Overall: Max Lateral/Vertical Ratio",

    "gyro_peak_overall": "Gyro: Max Angular Velocity",
    "gyro_peak_curve_avg": "Gyro: Avg Peak velocity (Curves)",
    "gyro_peak_curve_max": "Gyro: Max Peak velocity (Curves)",
    "gyro_z_peak_curve_avg": "Gyro: Avg Peak Yaw (Curves)",
    "gyro_z_clean_ratio_curve_mean": "Gyro: Steering Efficiency Ratio",
    "gyro_reversal_rate_avg": "Gyro: Active Steering Reversal Rate",
    "gyro_reversal_rate_curves": "Gyro: Curve Reversal Rate",
    "gyro_jerk_rms_avg": "Gyro: Smoothness (Gyro Jerk)",

    "x_mean": "X-axis acceleration mean",
    "x_std": "X-axis acceleration std",
    "y_mean": "Y-axis acceleration mean",
    "y_std": "Y-axis acceleration std",
    "z_mean": "Z-axis acceleration mean",
    "z_std": "Z-axis acceleration std",
}

FEATURE_FULL_NAMES_LV = {
    "ax_mean": "x ass paātrinājuma vidējais",
    "ay_mean": "y ass paātrinājuma vidējais",
    "az_mean": "z ass paātrinājuma vidējais",
    "ax_std": "x ass paātrinājuma standartnovirze",
    "ay_std": "y ass paātrinājuma standartnovirze",
    "az_std": "z ass paātrinājuma standartnovirze",
    "ax_min": "x ass paātrinājuma minimums",
    "ay_min": "y ass paātrinājuma minimums",
    "az_min": "z ass paātrinājuma minimums",
    "ax_max": "x ass paātrinājuma maksimums",
    "ay_max": "y ass paātrinājuma maksimums",
    "az_max": "z ass paātrinājuma maksimums",
    "ax_p25": "x ass paātrinājuma 25. procentile",
    "ay_p25": "y ass paātrinājuma 25. procentile",
    "az_p25": "z ass paātrinājuma 25. procentile",
    "ax_p75": "x ass paātrinājuma 75. procentile",
    "ay_p75": "y ass paātrinājuma 75. procentile",
    "az_p75": "z ass paātrinājuma 75. procentile",
    "ax_p95": "x ass paātrinājuma 95. procentile",
    "ay_p95": "y ass paātrinājuma 95. procentile",
    "az_p95": "z ass paātrinājuma 95. procentile",
    "ax_p95_abs": "x ass paātrinājuma absolūtā 95. procentile",
    "ay_p95_abs": "y ass paātrinājuma absolūtā 95. procentile",
    "az_p95_abs": "z ass paātrinājuma absolūtā 95. procentile",
    "ay_abs_p95": "sānass pārslodzes intensitāte (95. proc.)",
    "ax_iqr": "x ass paātrinājuma starpkvartiļu amplitūda",
    "ay_iqr": "y ass paātrinājuma starpkvartiļu amplitūda",
    "az_iqr": "z ass paātrinājuma starpkvartiļu amplitūda",
    "ax_abs_mean": "x ass paātrinājuma absolūtais vidējais",
    "ay_abs_mean": "y ass paātrinājuma absolūtais vidējais",
    "az_abs_mean": "z ass paātrinājuma absolūtais vidējais",
    "ax_jerk_rms": "x ass rāviena RMS",
    "ay_jerk_rms": "y ass rāviena RMS",
    "az_jerk_rms": "z ass rāviena RMS",
    "az_integral": "z ass paātrinājuma integrālis",
    "az_centered_integral": "z ass centrēta paātrinājuma integrālis",
    "g_mag_mean": "vektora moduļa vidējais",
    "g_mag_max": "vektora moduļa maksimums",
    "g_mag_p95": "vektora moduļa 95. procentile",
    "lateral_to_vertical_ratio": "sānass-z ass pārslodzes attiecība",
    "inward_steering_fraction": "iekšējās stūrēšanas īpatsvars (kopējais)",
    "radial_positive_fraction": "radiālā paātrinājuma pozitīvais īpatsvars",
    "ax_zero_crossings": "x ass nulles šķērsojumu skaits",
    "ay_zero_crossings": "y ass nulles šķērsojumu skaits",
    "az_zero_crossings": "z ass nulles šķērsojumu skaits",
    "ax_sign_flips_per_s": "x ass zīmes maiņas biežums sekundē",
    "az_peak_position": "z ass maksimuma relatīvā pozīcija",
    "az_fwhm_ratio": "z ass FWHM attiecība",
    "gyro_mag_mean": "žiroskopa moduļa vidējais",
    "gyro_mag_max": "žiroskopa moduļa maksimums (kopējais)",
    "gyro_mag_integral": "žiroskopa moduļa integrālis",
    "gyro_mag_jerk_rms": "žiroskopa moduļa rāviena RMS",
    "gyro_z_integral_signed": "z ass leņķiskā ātruma virzienu saglabājošs integrālis",
    "gyro_z_integral_abs": "z ass leņķiskā ātruma absolūtais integrālis",
    "gyro_z_steering_efficiency": "stūrēšanas efektivitātes koeficients (atvasinātais)",
    "gyro_z_sign_flips_per_s": "stūrēšanas virziena maiņas biežums",
    "gyro_x_peak": "rullēšanas ātruma maksimums (kopējais)",
    "gyro_y_peak": "sasvēršanās ātruma maksimums (kopējais)",
    "gyro_z_peak": "griešanās ātruma maksimums (kopējais)",
    "ay_zero_cross_rate": "sānass nulles šķērsojumu biežums",
    "ax_zero_cross_rate": "garenass nulles šķērsojumu biežums",
    "ay_signed_mean": "vidējā sānass virziena pārslodze",
    "ay_signed_p95": "maksimālā sānass virziena pārslodze",
    "ay_signed_min": "minimālā sānass virziena pārslodze",
    "ay_inward_fraction": "iekšējās stūrēšanas īpatsvars",
    "ay_abs_avg": "sānass absolūtais vidējais",
    "g_total_max": "maksimālā kopējā pārslodze",
    "g_total_mean": "vidējā kopējā pārslodze",
    "g_lat_vert_p95": "sānass un z ass pārslodzes attiecība",
    "gyro_jerk_rms": "leņķiskās kustības gludums",
    "gyro_z_peak_abs": "griešanās ātruma maksimums",
    "gyro_x_peak_abs": "rullēšanas ātruma maksimums",
    "gyro_y_peak_abs": "sasvēršanās ātruma maksimums",
    "gyro_z_clean_ratio": "stūrēšanas efektivitātes koeficients",
    "gyro_mag_peak": "leņķiskā ātruma maksimums",
    "wiggle_count": "līkumu skaits",
    "prev_is_straight": "iepriekšējais ir taisne",
    "prev_is_curve": "iepriekšējais ir virāža",
}

PREFIX_NAMES_LV = {
    "start": "Starts",
    "curve": "Virāža",
    "straight": "Taisne",
    "entry": "Ieeja",
    "apex": "Apekss",
    "exit": "Izeja",
    "prev_straight": "Iepr. taisne",
    "prev_curve": "Iepr. virāža",
    "ride": "Brauciens",
    "overall": "Kopumā",
}

STAT_NAMES_LV = {
    "mean": "vidējais",
    "p90": "90. procentile",
    "p95": "95. procentile",
    "max": "maksimums",
    "min": "minimums",
    "std": "standartnovirze",
    "sum": "summa",
    "abs_mean": "absolūtais vidējais",
    "first_half_sum": "pirmās puses summa",
    "first_quarter_mean": "pirmās ceturtdaļas vidējais",
}

RIDE_LEVEL_NAMES_LV = {
    "Ride: g_mag Mean": "Vektora moduļa vidējā vērtība",
    "Ride: g_mag P95": "Vektora moduļa 95. procentile",
    "Ride: g_mag Max": "Vektora moduļa maksimuma vērtība",
    "Ride: az Mean": "Z ass vidējā vērtība",
    "Ride: az P95": "Z ass 95. procentile",
    "Ride: ax Mean": "X ass vidējā vērtība",
    "Ride: ax Abs Mean": "X ass absolūtais vidējā vērtība",
    "Ride: ay Abs P95": "Y ass absolūtā 95. procentile",
    "Ride: ax First Half Sum": "X ass pirmās puses summa",
    "Ride: ax First Quarter Mean": "X ass pirmās ceturtdaļas vvidējā vērtība",
    "Ride: Jerk RMS": "Brauciens: rāviena RMS",
    "Ride: gz Abs Mean": "Žiroskopa z ass absolūtais vidējā vērtība",
    "Ride: gz P95 Abs": "Žiroskopa z ass absolūtā 95. procentile",
    "Ride: gz Sign Flips Per S": "Stūrēšanas svārstību biežums",
    "Start: Push Impulse": "Starts: atgrūdiena impulss",
    "Curve: Steering Wobble Rate": "Virāža: stūrēšanas svārstību biežums",
    "Straight: Steering Wobble Rate": "Taisne: stūrēšanas svārstību biežums",
    "Curve: Lateral Load Consistency": "Virāža: sānass slodzes vienmērīgums",
    "Overall: Curve vs Straight Jerk Gap": "Rāviena starpība starp virāžām un taisniem posmiem",
    "Curve: Lateral G-Force Intensity (95th Pct)": "Virāža: sānass pārslodzes intensitāte (95. procentile)",
    "Curve: Longitudinal Smoothness (Jerk) (Mean)": "Virāža: garenass gludums (rāviens, vidējais)",
}

SEGMENT_LEVEL_NAMES_LV = {
    "Segment Index": "Segmenta indekss",
    "Segment Kind": "Segmenta tips",
    "Duration (s)": "Ilgums (s)",
    "Duration Z-Score": "Ilguma z-rādītājs",
    "Z-Score Source": "Z-rādītāja avots",
    "Vertical G-Force Peak": "Z ass pārslodzes maksimums",
    "Vertical G-Force Min": "Z ass pārslodzes minimums",
    "Average Vertical G-Force": "Vidējā z ass pārslodze",
    "Vertical G-Force Std": "Z ass pārslodzes standartnovirze",
    "Vertical G-Force IQR": "Z ass pārslodzes starpkvartiļu amplitūda",
    "Vertical G-Force 95th Pct": "Z ass pārslodze (95. procentile)",
    "Average Lateral G-Force": "Vidējā sānass pārslodze",
    "Lateral G-Force Intensity (95th Pct)": "Sānass pārslodzes intensitāte (95. procentile)",
    "Average Directional Side-Force": "Vidējā sānass virziena pārslodze",
    "Peak Directional Side-Force": "Maksimālā sānass virziena pārslodze",
    "Min Directional Side-Force": "Minimālā sānass virziena pārslodze",
    "Inward Steering Fraction": "Iekšējās stūrēšanas īpatsvars",
    "Steering Activity / Wobble Rate": "Stūrēšanas aktivitāte / svārstību biežums",
    "Longitudinal G-Force Std": "Garenass pārslodzes standartnovirze",
    "Peak Longitudinal G-Force": "Maksimālā garenass pārslodze",
    "Longitudinal Reversal Rate": "Garenass apgriešanās biežums",
    "Longitudinal Smoothness (Jerk)": "Garenass gludums (rāviens)",
    "Lateral Smoothness (Jerk)": "Sānass gludums (rāviens)",
    "Vertical Smoothness (Jerk)": "Z ass gludums (rāviens)",
    "Vertical Peak Position": "Z ass maksimuma pozīcija",
    "Vertical Peak Width Ratio": "Z ass maksimuma platuma attiecība",
    "Peak Total Combined G-Force": "Maksimālā kopējā pārslodze",
    "Avg Total Combined G-Force": "Vidējā kopējā pārslodze",
    "Lateral-to-Vertical Force Ratio": "Sānass un z ass pārslodzes attiecība",
    "Angular Velocity Peak": "Maksimālais leņķiskais ātrums",
    "Avg Angular Velocity": "Vidējais leņķiskais ātrums",
    "Yaw Rate Peak": "Maksimālais griešanās ātrums",
    "Steering Efficiency Ratio": "Stūrēšanas efektivitātes koeficients",
    "Steering Reversal Rate": "Stūrēšanas virziena maiņas biežums",
    "Roll Rate Peak": "Maksimālais rullēšanas ātrums",
    "Pitch Rate Peak": "Maksimālais sasvēršanās ātrums",
    "Angular Movement Smoothness": "Leņķiskās kustības gludums",

    "Entry: Vertical G-Force Peak": "Ieeja: z ass pārslodzes maksimums",
    "Entry: Average Vertical G-Force": "Ieeja: vidējā z ass pārslodze",
    "Entry: Vertical G-Force Std": "Ieeja: z ass pārslodzes standartnovirze",
    "Entry: Lateral G-Force Intensity (95th Pct)": "Ieeja: sānass pārslodzes intensitāte (95. procentile)",
    "Entry: Average Directional Side-Force": "Ieeja: vidējā sānass virziena pārslodze",
    "Entry: Steering Activity / Wobble Rate": "Ieeja: stūrēšanas aktivitāte / svārstību biežums",
    "Entry: Peak Longitudinal G-Force": "Ieeja: maksimālā garenass pārslodze",
    "Entry: Longitudinal Smoothness (Jerk)": "Ieeja: garenass gludums (rāviens)",
    "Entry: Lateral Smoothness (Jerk)": "Ieeja: sānass gludums (rāviens)",
    "Entry: Lateral-to-Vertical Force Ratio": "Ieeja: sānass un z ass pārslodzes attiecība",
    "Entry: Angular Velocity Peak": "Ieeja: maksimālais leņķiskais ātrums",
    "Entry: Avg Angular Velocity": "Ieeja: vidējais leņķiskais ātrums",
    "Entry: Yaw Rate Peak": "Ieeja: maksimālais griešanās ātrums",
    "Entry: Steering Reversal Rate": "Ieeja: stūrēšanas virziena maiņas biežums",
    "Entry: Angular Movement Smoothness": "Ieeja: leņķiskās kustības gludums",

    "Apex: Vertical G-Force Peak": "Apekss: z ass pārslodzes maksimums",
    "Apex: Average Vertical G-Force": "Apekss: vidējā z ass pārslodze",
    "Apex: Vertical G-Force Std": "Apekss: z ass pārslodzes standartnovirze",
    "Apex: Lateral G-Force Intensity (95th Pct)": "Apekss: sānass pārslodzes intensitāte (95. procentile)",
    "Apex: Average Directional Side-Force": "Apekss: vidējā sānass virziena pārslodze",
    "Apex: Steering Activity / Wobble Rate": "Apekss: stūrēšanas aktivitāte / svārstību biežums",
    "Apex: Peak Longitudinal G-Force": "Apekss: maksimālā garenass pārslodze",
    "Apex: Longitudinal Smoothness (Jerk)": "Apekss: garenass gludums (rāviens)",
    "Apex: Lateral Smoothness (Jerk)": "Apekss: sānass gludums (rāviens)",
    "Apex: Lateral-to-Vertical Force Ratio": "Apekss: sānass un z ass pārslodzes attiecība",
    "Apex: Angular Velocity Peak": "Apekss: maksimālais leņķiskais ātrums",
    "Apex: Avg Angular Velocity": "Apekss: vidējais leņķiskais ātrums",
    "Apex: Yaw Rate Peak": "Apekss: maksimālais griešanās ātrums",
    "Apex: Steering Reversal Rate": "Apekss: stūrēšanas virziena maiņas biežums",
    "Apex: Angular Movement Smoothness": "Apekss: leņķiskās kustības gludums",

    "Exit: Vertical G-Force Peak": "Izeja: z ass pārslodzes maksimums",
    "Exit: Average Vertical G-Force": "Izeja: vidējā z ass pārslodze",
    "Exit: Vertical G-Force Std": "Izeja: z ass pārslodzes standartnovirze",
    "Exit: Lateral G-Force Intensity (95th Pct)": "Izeja: sānass pārslodzes intensitāte (95. procentile)",
    "Exit: Average Directional Side-Force": "Izeja: vidējā sānass virziena pārslodze",
    "Exit: Steering Activity / Wobble Rate": "Izeja: stūrēšanas aktivitāte / svārstību biežums",
    "Exit: Peak Longitudinal G-Force": "Izeja: maksimālā garenass pārslodze",
    "Exit: Longitudinal Smoothness (Jerk)": "Izeja: garenass gludums (rāviens)",
    "Exit: Lateral Smoothness (Jerk)": "Izeja: sānass gludums (rāviens)",
    "Exit: Lateral-to-Vertical Force Ratio": "Izeja: sānass un z ass pārslodzes attiecība",
    "Exit: Angular Velocity Peak": "Izeja: maksimālais leņķiskais ātrums",
    "Exit: Avg Angular Velocity": "Izeja: vidējais leņķiskais ātrums",
    "Exit: Yaw Rate Peak": "Izeja: maksimālais griešanās ātrums",
    "Exit: Steering Reversal Rate": "Izeja: stūrēšanas virziena maiņas biežums",
    "Exit: Angular Movement Smoothness": "Izeja: leņķiskās kustības gludums",

    "Previous Segment Kind": "Iepriekšējā segmenta tips",
    "Previous Segment Duration": "Iepriekšējā segmenta ilgums",
    "Previous Is Straight": "Iepriekšējais ir taisne",
    "Previous Is Curve": "Iepriekšējais ir virāža",
    "Prev Straight: Vertical G-Force Peak": "Iepr. tais. posm: z ass pārslodzes maksimums",
    "Prev Curve: Vertical G-Force Peak": "Iepr. virāža: z ass pārslodzes maksimums",
    "Prev Straight: Lateral G-Force Intensity (95th Pct)": "Iepr. tais. posm: sānass pārslodzes intensitāte (95. proc.)",
    "Prev Curve: Lateral G-Force Intensity (95th Pct)": "Iepr. virāža: sānass pārslodzes intensitāte (95. proc.)",
    "Prev Straight: Longitudinal Smoothness (Jerk)": "Iepr. tais. posm: garenass gludums (rāviens)",
    "Prev Curve: Longitudinal Smoothness (Jerk)": "Iepr. virāža: garenass gludums (rāviens)",
    "Prev Straight: Lateral-to-Vertical Force Ratio": "Iepr. tais. posm: sānass un z ass pārslodzes attiecība",
    "Prev Curve: Lateral-to-Vertical Force Ratio": "Iepr. virāža: sānass un z ass pārslodzes attiecība",
    "Prev Straight: Peak Total Combined G-Force": "Iepr. tais. posm: maks. kopējā pārslodze",
    "Prev Curve: Peak Total Combined G-Force": "Iepr. virāža: maks. kopējā pārslodze",
    "Prev Straight: Steering Efficiency Ratio": "Iepr. tais. posm: stūrēšanas efektivitātes koeficients",
    "Prev Curve: Steering Efficiency Ratio": "Iepr. virāža: stūrēšanas efektivitātes koeficients",
}


def translate_feature_name(en_name):
    if en_name in RIDE_LEVEL_NAMES_LV:
        return RIDE_LEVEL_NAMES_LV[en_name]
    if en_name in SEGMENT_LEVEL_NAMES_LV:
        return SEGMENT_LEVEL_NAMES_LV[en_name]
    return en_name


def bilingual_label(en_name):
    lv_name = translate_feature_name(en_name)
    if lv_name == en_name:
        return en_name
    return f"{lv_name}"